#!/bin/sh

GIT_BASH_PATH="/c/Program Files/Git/usr/bin"
NPM_PATH="/c/Program Files/nodejs/npm.cmd"

# Temporarily add Git Bash to PATH if it's not already in the PATH
if ! command -v bash &> /dev/null; then
    export PATH="$PATH:$GIT_BASH_PATH"
fi

commitlint --edit $1

# Direct run NPM if it's not in the PATH
if [ -f "$NPM_PATH" ]; then
    "$NPM_PATH" run typescript:check
else
    npm run typescript:check
fi
