name: Lint Commit

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  main:
    name: Lint Commit Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
